version: "3.8"

services:
  db:
    image: postgres:15
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3119
      POSTGRES_DB: musicShop
    ports:
      - "5435:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
