version: "3.8"

services:
  db:
    image: postgres:15
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3119
      POSTGRES_DB: musicShop
    ports:
      - "5435:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    container_name: musicshop_app
    build: .  # Lê o Dockerfile na raiz e executa a multi-stage build
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: 3119
      DB_NAME: musicShop

volumes:
  db-data:
